name: UHCHost
version: 0.8.2
author: Lastril
main: fr.lastril.helheimhost.UhcHost
commands:
  h:
    description: Command of Host.
  host:
    description: Command of Host.
  scenarios:
    description: Command show actives scenarios.
  