name: Group-UHC
version: 0.9.8
authors: [Lastril]
main: fr.lastril.uhchost.UhcHost
commands:
  test:
    description: Test command.
  h:
    description: Command of Host.
    aliases: host
  inv:
    description: Command to show start inventory.
  invsee:
    description: Command to show player inventory.
    aliases:
      - oi
  revive:
    description: Command to revive players ingame.
  setgroupes:
    aliases:
      - groupes
      - groupe
      - group
      - setgroupe
      - setgroup
    description: Commande to set groups.

  doc:
    description: Command to show document of UHC gamemode.
  maj:
    description : Command to show MAJ on plugin.

  say:
    description: Command say.
  mumble:
    description: Command to show Mumble.
  discord:
    description: Command to show Discord Server.
  help:
    aliases:
      - aide
      - aides
    description: Command to help players for commands.
  rules:
    description: Command to see rules.
  scenarios:
    description: Command show actives scenarios.

  role:
    description: t
  don:
    description: Command LG Couple.

  lg:
    description: Command of LG Mode.
  b:
    aliases:
      - bleach
    description: Command of Bleach Mode.
  ns:
    aliases:
      - narutos
    description: Command of Naruto Mode.
  ds:
    aliases:
      - demonslayer
    description: Command of DemonSlayer Mode.
  