name: UHCHost
version: 0.9.7
author: Lastril
main: fr.lastril.uhchost.UhcHost
commands:
  h:
    description: Command of Host.
    aliases: host
  scenarios:
    description: Command show actives scenarios.
  lg:
    description: Command of LG Mode.
  role:
    description: Command to see Role.
  potions:
    description: Command active potions.
  loots:
    description: Command loots settings.
  test:
    description: Test command.
  say:
    description: Command say.
  setgroupes:
    aliases:
      - groupes
    description: Commande to set groups.
  b:
    description: Command of Bleach Mode.
  rules:
    description: Command to see rules.
  revive:
    description: Command to revive players ingame.
  narutos:
    aliases:
      - ns
    description: Command of Naruto Mode.
  