name: UHCHost
version: 0.9.2
author: Lastril
main: fr.lastril.uhchost.UhcHost
commands:
  h:
    description: Command of Host.
    aliases: host
  scenarios:
    description: Command show actives scenarios.
  lg:
    description: Command of LG Mode.
  role:
    description: Command to see Role.
  potions:
    description: Command active potions.
  loots:
    description: Command loots settings.
  